parameters:
    ezsettings.default.content_edit.templates.edit: '@@EzSystemsRepositoryForms/Content/content_edit.html.twig'
    ezsettings.default.content_edit.templates.create: '@@EzSystemsRepositoryForms/Content/content_edit.html.twig'
    ezsettings.default.content_edit.templates.create_draft: '@@EzSystemsRepositoryForms/Content/content_create_draft.html.twig'
    ezsettings.default.user_edit.templates.update: '@@EzSystemsRepositoryForms/Content/content_edit.html.twig'
    ezsettings.default.user_edit.templates.create: '@@EzSystemsRepositoryForms/Content/content_edit.html.twig'
    ezsettings.default.limitation_value_templates:
        - { template: '@@EzSystemsRepositoryForms/limitation_values.html.twig', priority: 0 }

    ezsettings.default.content_edit_view: {}
    ezsettings.default.content_create_view: {}
