services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    eZ\Publish\API\Repository\FieldTypeService: '@ezpublish.api.service.field_type'

    #
    # FieldTypes
    #

    EzSystems\RepositoryForms\Form\Type\FieldType\:
        resource: '../../../lib/Form/Type/FieldType/*'
        tags:
            - { name: 'form.type' }

    EzSystems\RepositoryForms\Form\Type\FieldType\CountryFieldType:
        arguments:
            $countriesInfo: '%ezpublish.fieldType.ezcountry.data%'

    #
    # FormMappers
    #

    EzSystems\RepositoryForms\FieldType\Mapper\AuthorFormMapper:
        tags:
            - { name: ezplatform.field_type.form_mapper.value, fieldType: ezauthor }

    EzSystems\RepositoryForms\FieldType\Mapper\BinaryFileFormMapper:
        tags:
            - { name: ezplatform.field_type.form_mapper.value, fieldType: ezbinaryfile }

    EzSystems\RepositoryForms\FieldType\Mapper\CheckboxFormMapper:
        tags:
            - { name: ezplatform.field_type.form_mapper.value, fieldType: ezboolean }

    EzSystems\RepositoryForms\FieldType\Mapper\SelectionFormMapper:
        tags:
            - { name: ezplatform.field_type.form_mapper.value, fieldType: ezselection }

    EzSystems\RepositoryForms\FieldType\Mapper\CountryFormMapper:
        tags:
            - { name: ezplatform.field_type.form_mapper.value, fieldType: ezcountry }

    EzSystems\RepositoryForms\FieldType\Mapper\DateFormMapper:
        tags:
            - { name: ezplatform.field_type.form_mapper.value, fieldType: ezdate }

    EzSystems\RepositoryForms\FieldType\Mapper\DateTimeFormMapper:
        tags:
            - { name: ezplatform.field_type.form_mapper.value, fieldType: ezdatetime }

    EzSystems\RepositoryForms\FieldType\Mapper\FloatFormMapper:
        tags:
            - { name: ezplatform.field_type.form_mapper.value, fieldType: ezfloat }

    EzSystems\RepositoryForms\FieldType\Mapper\ImageFormMapper:
        tags:
            - { name: ezplatform.field_type.form_mapper.value, fieldType: ezimage }

    EzSystems\RepositoryForms\FieldType\Mapper\IntegerFormMapper:
        tags:
            - { name: ezplatform.field_type.form_mapper.value, fieldType: ezinteger }

    EzSystems\RepositoryForms\FieldType\Mapper\ISBNFormMapper:
        tags:
            - { name: ezplatform.field_type.form_mapper.value, fieldType: ezisbn }

    EzSystems\RepositoryForms\FieldType\Mapper\MediaFormMapper:
        tags:
            - { name: ezplatform.field_type.form_mapper.value, fieldType: ezmedia }

    EzSystems\RepositoryForms\FieldType\Mapper\AbstractRelationFormMapper:
        abstract: true
        arguments:
            $contentTypeService: '@ezpublish.api.service.content_type'

    EzSystems\RepositoryForms\FieldType\Mapper\RelationFormMapper:
        parent: EzSystems\RepositoryForms\FieldType\Mapper\AbstractRelationFormMapper
        autowire: true
        autoconfigure: false
        public: false
        tags:
            - { name: ezplatform.field_type.form_mapper.value, fieldType: ezobjectrelation }

    EzSystems\RepositoryForms\FieldType\Mapper\RelationListFormMapper:
        parent: EzSystems\RepositoryForms\FieldType\Mapper\AbstractRelationFormMapper
        autowire: true
        autoconfigure: false
        public: false
        tags:
            - { name: ezplatform.field_type.form_mapper.value, fieldType: ezobjectrelationlist }

    EzSystems\RepositoryForms\FieldType\Mapper\TextLineFormMapper:
        tags:
            - { name: ezplatform.field_type.form_mapper.value, fieldType: ezstring }

    EzSystems\RepositoryForms\FieldType\Mapper\TextBlockFormMapper:
        tags:
            - { name: ezplatform.field_type.form_mapper.value, fieldType: eztext }

    EzSystems\RepositoryForms\FieldType\Mapper\TimeFormMapper:
        tags:
            - { name: ezplatform.field_type.form_mapper.value, fieldType: eztime }

    EzSystems\RepositoryForms\FieldType\Mapper\FormTypeBasedFieldValueFormMapper:
        abstract: true

    EzSystems\RepositoryForms\FieldType\Mapper\UserAccountFieldValueFormMapper:
        tags:
            - { name: ezplatform.field_type.form_mapper.value, fieldType: ezuser }

    EzSystems\RepositoryForms\FieldType\Mapper\UrlFormMapper:
        tags:
            - { name: ezplatform.field_type.form_mapper.value, fieldType: ezurl }

    EzSystems\RepositoryForms\FieldType\Mapper\MapLocationFormMapper:
        tags:
            - { name: ezplatform.field_type.form_mapper.value, fieldType: ezgmaplocation }

    EzSystems\RepositoryForms\FieldType\Mapper\KeywordFormMapper:
        tags:
            - { name: ezplatform.field_type.form_mapper.value, fieldType: ezkeyword }

    ezplatform.content_forms.field_type.form_mapper.ezemail:
        parent: EzSystems\RepositoryForms\FieldType\Mapper\FormTypeBasedFieldValueFormMapper
        autowire: true
        autoconfigure: false
        public: false
        tags:
            - { name: ezplatform.field_type.form_mapper.value, fieldType: ezemail }
        calls:
            - [setFormType, ['Symfony\Component\Form\Extension\Core\Type\EmailType']]

    EzSystems\RepositoryForms\FieldType\Mapper\ImageAssetFormMapper:
        tags:
            - { name: ezplatform.field_type.form_mapper.value, fieldType: ezimageasset }
